server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_database?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.mytest.dao.domain